# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  workflow_dispatch:
    branches:
      - ECS-23-Multithread-graphics

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: HostileEngine/HostileEngine.sln
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
  VCPKG_DEFAULT_TRIPLET: "x64-windows"
  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

  TRIPLET: x64-windows

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    
    - name: Export GitHub Actions cache environment variables
      uses: actions/github-script@v6
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
          
    - name: vcpkg-install
      id: vcpkg
      uses: johnwason/vcpkg-action@v5
      with:
        manifest-dir: ${{ github.workspace }}/HostileEngine/HostileEngine/
        #pkgs: d3dx12 directxtk12 glfw3 flecs nlohmann-json tomlplusplus assimp directxtex[dx12]
        triplet: ${{env.TRIPLET}}
        token: ${{ github.token }}
        
    - name: vcpkg-integrate
      run: ${{ github.workspace }}\vcpkg\vcpkg integrate install
    
    - name: Boostrap vcpkg
      shell: pwsh
      run: ${{ github.workspace }}\vcpkg\bootstrap-vcpkg.bat

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
